os:
  - linux
  - windows

language: go
go:
  - 1.13.x

git:
  depth: false

env:
  - GO111MODULE=off

deploy:
  - provider: script
    cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux